---
- name: Cypress Dependencies
  apt:
      name:
          - libgtk2.0-0
          - libgtk-3-0
          - libnotify-dev
          - libgconf-2-4
          - libnss3
          - libxss1
          - libasound2
          - libxtst6
          - xauth
          - xvfb
      state: latest
      update_cache: true
