# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Psalm
        uses: docker://vimeo/psalm-github-actions

#  phpstan:
#    name: PHPStan
#    runs-on: ubuntu-18.04
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: PHPStan
#        uses: docker://oskarstark/phpstan-ga
#        with:
#          args: analyse -l max -c phpstan.neon ./src
#          secrets: "GITHUB_TOKEN"

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --diff --dry-run --allow-risky=yes
          secrets: "GITHUB_TOKEN"

  eslint:
    name: eslint
    runs-on: ubuntu-18.04
    steps:
      -   name: Checkout code
          uses: actions/checkout@v2

      -   name: eslint
          uses: reviewdog/action-eslint@v1
          with:
              github_token: ${{ secrets.github_token }}
              eslint_flags: 'assets/js'
